services:
  postgres:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: sukimise
      POSTGRES_USER: sukimise_user
      POSTGRES_PASSWORD: sukimise_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sukimise_user -d sukimise"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: golang:1.23-alpine
    # Backend is now internal only - no external port exposure
    # Access via frontend proxy or direct container access for debugging
    expose:
      - "${BACKEND_PORT:-8081}"
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://sukimise_user:sukimise_password@postgres:5432/sukimise?sslmode=disable}
      JWT_SECRET: ${JWT_SECRET:-your-jwt-secret-key}
      PORT: ${BACKEND_PORT:-8081}
      HOST: 0.0.0.0
      CGO_ENABLED: 0
      ADMIN_USERS: ${ADMIN_USERS}
      EDITOR_USERS: ${EDITOR_USERS}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:5173}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - uploads_data:/app/uploads
      - ./.env:/app/.env
    working_dir: /app
    command: sh -c "apk add --no-cache git && go mod download && go run cmd/server/main.go"

  frontend:
    image: node:18-alpine
    ports:
      - "${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}"
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:${BACKEND_PORT:-8081}}
      VITE_PORT: ${FRONTEND_PORT:-3000}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port ${FRONTEND_PORT:-3000}"
    depends_on:
      - backend

  discord-bot:
    image: golang:1.23-alpine
    ports:
      - "${BOT_PORT:-8082}:${BOT_PORT:-8082}"
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://sukimise_user:sukimise_password@postgres:5432/sukimise?sslmode=disable}
      SUKIMISE_API_URL: ${SUKIMISE_API_URL:-http://backend:${BACKEND_PORT:-8081}}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      BOT_PORT: ${BOT_PORT:-8082}
      CGO_ENABLED: 0
    depends_on:
      postgres:
        condition: service_healthy
      backend:
        condition: service_started
    volumes:
      - ./discord-bot:/app
    working_dir: /app
    command: sh -c "apk add --no-cache git && go mod download && go run cmd/main.go"

volumes:
  postgres_data:
  uploads_data:
